# Multi-stage Client container for React Build and Nginx serving
FROM node:18-alpine AS builder

WORKDIR /usr/src/app

COPY client/package*.json ./
RUN npm ci

COPY client/ .
RUN npm run build

FROM nginx:stable-alpine

COPY --from=builder /usr/src/app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/templates/default.conf.template

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
