const express = require('express');
const router = express.Router();
const { AuditLog, User } = require('../utils/db');
const { verifyToken } = require('../middleware/auth');
const { logAudit } = require('../utils/auditLogger');
const { Op } = require('sequelize');

/**
 * @route GET /api/audit/logs
 * @desc Get audit logs (paginated, filterable)
 * @access Private (city_admin, hospital_admin)
 */
router.get('/logs', verifyToken(['city_admin', 'hospital_admin']), async (req, res) => {
  const { category, severity, action, user_id, page = 1, limit = 50 } = req.query;
  const offset = (page - 1) * limit;

  const where = {};
  if (category) where.category = category;
  if (severity) where.severity = severity;
  if (action) where.action = action;
  if (user_id) where.user_id = user_id;

  // If hospital_admin, restrict to logs generated by users of the same hospital
  if (req.user.role === 'hospital_admin') {
    where[Op.or] = [
      { user_id: req.user.id },
      { 
        user_id: {
          [Op.in]: sequelize.literal(`(SELECT id FROM users WHERE hospital_id = '${req.user.hospital_id}')`)
        }
      }
    ];
  }

  try {
    const { count, rows } = await AuditLog.findAndCountAll({
      where,
      limit: parseInt(limit),
      offset: parseInt(offset),
      order: [['createdAt', 'DESC']],
      include: [
        {
          model: User,
          as: 'user',
          attributes: ['id', 'name', 'email', 'role']
        }
      ]
    });

    return res.json({
      total: count,
      pages: Math.ceil(count / limit),
      currentPage: parseInt(page),
      logs: rows
    });
  } catch (err) {
    console.error('[AUDIT ROUTE ERROR]', err.message);
    return res.status(500).json({ error: 'Failed to retrieve audit logs' });
  }
});

/**
 * @route POST /api/audit/unmask-alarm
 * @desc Log a critical patient data unmasking action and broadcast an alert
 * @access Private (Authenticated users)
 */
router.post('/unmask-alarm', verifyToken(), async (req, res) => {
  const { patientId, reason, patientName } = req.body;
  if (!patientId || !reason) {
    return res.status(400).json({ error: 'Patient ID and reason for unmasking are required' });
  }

  try {
    await logAudit(
      'PATIENT_UNMASK',
      'PATIENT_UNMASK',
      {
        patientId,
        patientName,
        reason,
        resource: 'Patient',
        resourceId: patientId,
        ipAddress: req.ip || req.connection.remoteAddress,
        userId: req.user.id,
        userEmail: req.user.email,
        userName: req.user.name,
        userRole: req.user.role
      },
      'CRITICAL',
      req.user.id,
      req.ip || req.connection.remoteAddress
    );

    return res.json({ message: 'Identity unmasking request authorized and audited' });
  } catch (err) {
    console.error('[UNMASK ALARM ERROR]', err.message);
    return res.status(500).json({ error: 'Failed to execute unmask audit alarm' });
  }
});

/**
 * @route GET /api/audit/consent-log
 * @desc Retrieve consent-related operations (DPDP compliance monitoring)
 * @access Private (city_admin, hospital_admin)
 */
router.get('/consent-log', verifyToken(['city_admin', 'hospital_admin']), async (req, res) => {
  try {
    const logs = await AuditLog.findAll({
      where: {
        category: 'CONSENT'
      },
      order: [['createdAt', 'DESC']],
      limit: 100,
      include: [
        {
          model: User,
          as: 'user',
          attributes: ['id', 'name', 'email', 'role']
        }
      ]
    });
    return res.json(logs);
  } catch (err) {
    return res.status(500).json({ error: 'Failed to fetch consent logs' });
  }
});

/**
 * @route GET /api/audit/suspicious-activity
 * @desc Fetch suspicious logs with WARNING/CRITICAL severity
 * @access Private (city_admin)
 */
router.get('/suspicious-activity', verifyToken(['city_admin']), async (req, res) => {
  try {
    const logs = await AuditLog.findAll({
      where: {
        severity: {
          [Op.in]: ['WARNING', 'CRITICAL']
        }
      },
      order: [['createdAt', 'DESC']],
      limit: 100,
      include: [
        {
          model: User,
          as: 'user',
          attributes: ['id', 'name', 'email', 'role']
        }
      ]
    });
    return res.json(logs);
  } catch (err) {
    return res.status(500).json({ error: 'Failed to retrieve suspicious activities' });
  }
});

module.exports = router;
